# Generated by Django 5.2 on 2026-01-10 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(unique=True)),
                ('tree_id', models.CharField(blank=True, max_length=50, null=True)),
                ('species_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dovt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dbh', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('spread', models.FloatField(blank=True, null=True)),
                ('road_name', models.CharField(blank=True, max_length=255, null=True)),
                ('veg_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lu_hm', models.CharField(blank=True, max_length=50, null=True)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
            ],
        ),
    ]
