# Generated by Django 5.2 on 2026-01-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeinventory',
            old_name='lu_hm',
            new_name='lu_hmd',
        ),
    ]
