# Generated by Django 5.2 on 2026-01-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0002_rename_lu_hm_treeinventory_lu_hmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeinventory',
            old_name='dovt_id',
            new_name='ovt_id',
        ),
    ]
