# Generated by Django 5.2 on 2026-01-11 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0003_rename_dovt_id_treeinventory_ovt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeinventory',
            name='import_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
