# Generated by Django 5.2 on 2026-01-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0004_alter_treeinventory_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeinventory',
            name='tree_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TreePhotoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tree_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_urls', to='treeinvs.treeinventory', to_field='tree_id')),
            ],
        ),
    ]
