# Generated by Django 5.2 on 2026-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0006_alter_treephotourl_tree_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treephotourl',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
