# Generated by Django 5.2 on 2026-01-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeinvs', '0007_alter_treephotourl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treephotourl',
            name='tree_tag',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='treeinvs.treeinventory', to_field='tree_id'),
        ),
    ]
